// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PickAndDropBackEnd.Data;

namespace PickAndDropBackEnd.Migrations
{
    [DbContext(typeof(ComplaintsDbContext))]
    [Migration("20190912072746_InitialDataBase")]
    partial class InitialDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("PickAndDropBackEnd.Models.Complaints", b =>
                {
                    b.Property<long>("ComplaintId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ComplaintContent")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("CustomerName")
                        .IsRequired();

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.HasKey("ComplaintId");

                    b.ToTable("Complaints");
                });
#pragma warning restore 612, 618
        }
    }
}
